meta_product_name: "Loothuntr ğŸ´â€â˜ ï¸"
meta_title: "Loothuntr - L'aventure grandeur nature"
meta_description: "LootHuntr est LA plateforme qui vous permet de dÃ©couvrir des quÃªtes mystÃ©rieuses et excitantes, rencontrer les plus grands aventuriers de notre gÃ©nÃ©ration et organiser votre prochaine quÃªte !"
meta_image: "imagebanner.png" # should exist in `app/assets/images/`
