meta_product_name: "Loothuntr ğŸ´â€â˜ ï¸"
meta_title: "Loothuntr ğŸ´â€â˜ ï¸ - L'aventure grandeur nature"
meta_description: "LootHuntr est LA plateforme qui vous permet de dÃ©couvrir des quÃªtes mystÃ©rieuses et excitantes, rencontrer les plus grands aventuriers de notre gÃ©nÃ©ration et organiser votre prochaine quÃªte !"
meta_image: "http://www.loothuntr.co/assets/imagebanner-c1d32082594aa033b87b3ab148cdf99bb25232c0bf5ec684aa0f7623519f904e.png" # should exist in `app/assets/images/`
